[package]
name = "gdrust-trinkets"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = "~0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
macros = { path = "/macros" }

